// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This code is generated by Magic Modules using the following:
//
//     Configuration: https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/products/cloudtrace/TraceSink.yaml
//     Template:      https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/tgc/resource_converter.go.tmpl
//
//     DO NOT EDIT this file directly. Any changes made to this file will be
//     overwritten during the next generation cycle.
//
// ----------------------------------------------------------------------------

package cloudtrace

import (
	"reflect"

	"github.com/GoogleCloudPlatform/terraform-google-conversion/v6/tfplan2cai/converters/google/resources/cai"
	"github.com/hashicorp/terraform-provider-google-beta/google-beta/tpgresource"
	transport_tpg "github.com/hashicorp/terraform-provider-google-beta/google-beta/transport"
)

const CloudTraceTraceSinkAssetType string = "cloudtrace.googleapis.com/TraceSink"

func ResourceConverterCloudTraceTraceSink() cai.ResourceConverter {
	return cai.ResourceConverter{
		AssetType: CloudTraceTraceSinkAssetType,
		Convert:   GetCloudTraceTraceSinkCaiObject,
	}
}

func GetCloudTraceTraceSinkCaiObject(d tpgresource.TerraformResourceData, config *transport_tpg.Config) ([]cai.Asset, error) {
	name, err := cai.AssetName(d, config, "//cloudtrace.googleapis.com/projects/{{project}}//traceSinks/{{name}}")
	if err != nil {
		return []cai.Asset{}, err
	}
	if obj, err := GetCloudTraceTraceSinkApiObject(d, config); err == nil {
		return []cai.Asset{{
			Name: name,
			Type: CloudTraceTraceSinkAssetType,
			Resource: &cai.AssetResource{
				Version:              "v2beta1",
				DiscoveryDocumentURI: "https://www.googleapis.com/discovery/v1/apis/cloudtrace/v2beta1/rest",
				DiscoveryName:        "TraceSink",
				Data:                 obj,
			},
		}}, nil
	} else {
		return []cai.Asset{}, err
	}
}

func GetCloudTraceTraceSinkApiObject(d tpgresource.TerraformResourceData, config *transport_tpg.Config) (map[string]interface{}, error) {
	obj := make(map[string]interface{})
	output_configProp, err := expandCloudTraceTraceSinkOutputConfig(d.Get("output_config"), d, config)
	if err != nil {
		return nil, err
	} else if v, ok := d.GetOkExists("output_config"); !tpgresource.IsEmptyValue(reflect.ValueOf(output_configProp)) && (ok || !reflect.DeepEqual(v, output_configProp)) {
		obj["output_config"] = output_configProp
	}

	return obj, nil
}

func expandCloudTraceTraceSinkOutputConfig(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	l := v.([]interface{})
	if len(l) == 0 || l[0] == nil {
		return nil, nil
	}
	raw := l[0]
	original := raw.(map[string]interface{})
	transformed := make(map[string]interface{})

	transformedDestination, err := expandCloudTraceTraceSinkOutputConfigDestination(original["destination"], d, config)
	if err != nil {
		return nil, err
	} else if val := reflect.ValueOf(transformedDestination); val.IsValid() && !tpgresource.IsEmptyValue(val) {
		transformed["destination"] = transformedDestination
	}

	return transformed, nil
}

func expandCloudTraceTraceSinkOutputConfigDestination(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	return v, nil
}
