// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This code is generated by Magic Modules using the following:
//
//     Configuration: https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/products/cloudrunv2/Job.yaml
//     Template:      https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/tgc_next/cai2hcl/resource_converter.go.tmpl
//
//     DO NOT EDIT this file directly. Any changes made to this file will be
//     overwritten during the next generation cycle.
//
// ----------------------------------------------------------------------------

package cloudrunv2

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"log"
	"reflect"
	"regexp"
	"strings"

	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/customdiff"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/id"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/logging"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/retry"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/structure"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
	"github.com/hashicorp/terraform-plugin-sdk/v2/terraform"

	"github.com/GoogleCloudPlatform/terraform-google-conversion/v7/pkg/cai2hcl/converters/utils"
	"github.com/GoogleCloudPlatform/terraform-google-conversion/v7/pkg/cai2hcl/models"
	"github.com/GoogleCloudPlatform/terraform-google-conversion/v7/pkg/caiasset"
	"github.com/GoogleCloudPlatform/terraform-google-conversion/v7/pkg/tgcresource"
	"github.com/GoogleCloudPlatform/terraform-google-conversion/v7/pkg/tpgresource"
	"github.com/GoogleCloudPlatform/terraform-google-conversion/v7/pkg/transport"
	transport_tpg "github.com/GoogleCloudPlatform/terraform-google-conversion/v7/pkg/transport"
	"github.com/GoogleCloudPlatform/terraform-google-conversion/v7/pkg/verify"

	"google.golang.org/api/googleapi"
)

var (
	_ = fmt.Sprintf
	_ = reflect.ValueOf
	_ = strings.Trim
	_ = diag.Diagnostic{}
	_ = customdiff.All
	_ = id.UniqueId
	_ = logging.LogLevel
	_ = log.Printf
	_ = retry.Retry
	_ = schema.Noop
	_ = structure.ExpandJsonFromString
	_ = validation.All
	_ = terraform.State{}
	_ = tgcresource.RemoveTerraformAttributionLabel
	_ = tpgresource.GetRegion
	_ = transport_tpg.Config{}
	_ = verify.ProjectRegex
	_ = googleapi.Error{}
	_ = json.Unmarshal
)

type CloudRunV2JobCai2hclConverter struct {
	name   string
	schema map[string]*schema.Schema
}

func NewCloudRunV2JobCai2hclConverter(provider *schema.Provider) models.Cai2hclConverter {
	schema := provider.ResourcesMap[CloudRunV2JobSchemaName].Schema

	return &CloudRunV2JobCai2hclConverter{
		name:   CloudRunV2JobSchemaName,
		schema: schema,
	}
}

// Convert converts asset to HCL resource blocks.
func (c *CloudRunV2JobCai2hclConverter) Convert(assets []caiasset.Asset, options *models.ResourceConverterOptions) ([]*models.TerraformResourceBlock, error) {
	if len(assets) > 1 {
		return nil, fmt.Errorf("multiple assets are not supported")
	}

	var blocks []*models.TerraformResourceBlock
	block, err := c.convertResourceData(assets[0], options)
	if err != nil {
		return nil, err
	}
	blocks = append(blocks, block)
	return blocks, nil
}

func (c *CloudRunV2JobCai2hclConverter) convertResourceData(asset caiasset.Asset, options *models.ResourceConverterOptions) (*models.TerraformResourceBlock, error) {
	if asset.Resource == nil || asset.Resource.Data == nil {
		return nil, fmt.Errorf("asset resource data is nil")
	}

	var err error
	res := asset.Resource.Data
	config := transport.NewConfig()

	// This is a fake resource used to get fake d
	// d.Get will return empty map, instead of nil
	fakeResource := &schema.Resource{
		Schema: c.schema,
	}
	d := fakeResource.TestResourceData()

	assetNameParts := strings.Split(asset.Name, "/")

	var hclBlockName string
	if options != nil && options.ResourceName != "" {
		hclBlockName = options.ResourceName
	} else {
		hclBlockName = assetNameParts[len(assetNameParts)-1]
		digitRegex := regexp.MustCompile(`^\d+$`)
		nameValidator := regexp.MustCompile("^[a-zA-Z_][a-zA-Z0-9_-]*$")
		if digitRegex.MatchString(hclBlockName) || !nameValidator.MatchString(hclBlockName) {
			hasher := sha256.New()
			hasher.Write([]byte(hclBlockName))
			fullHash := hex.EncodeToString(hasher.Sum(nil))
			hclBlockName = fmt.Sprintf("resource%s", fullHash[:8])
		}
	}
	hclData := make(map[string]interface{})

	res, hclData, err = resourceCloudRunV2JobTgcDecoder(d, config, res, hclData)
	if err != nil {
		return nil, err
	}

	outputFields := map[string]struct{}{"conditions": struct{}{}, "create_time": struct{}{}, "creator": struct{}{}, "delete_time": struct{}{}, "effective_annotations": struct{}{}, "effective_labels": struct{}{}, "etag": struct{}{}, "execution_count": struct{}{}, "expire_time": struct{}{}, "generation": struct{}{}, "last_modifier": struct{}{}, "latest_created_execution": struct{}{}, "observed_generation": struct{}{}, "reconciling": struct{}{}, "terminal_condition": struct{}{}, "terraform_labels": struct{}{}, "uid": struct{}{}, "update_time": struct{}{}}
	utils.ParseUrlParamValuesFromAssetName(asset.Name, "//run.googleapis.com/projects/{{project}}/locations/{{location}}/jobs/{{name}}", outputFields, hclData)

	hclData["labels"] = flattenCloudRunV2JobLabels(res["labels"], d, config)
	hclData["annotations"] = flattenCloudRunV2JobAnnotations(res["annotations"], d, config)
	hclData["client"] = flattenCloudRunV2JobClient(res["client"], d, config)
	hclData["client_version"] = flattenCloudRunV2JobClientVersion(res["clientVersion"], d, config)
	hclData["launch_stage"] = flattenCloudRunV2JobLaunchStage(res["launchStage"], d, config)
	hclData["binary_authorization"] = flattenCloudRunV2JobBinaryAuthorization(res["binaryAuthorization"], d, config)
	hclData["template"] = flattenCloudRunV2JobTemplate(res["template"], d, config)

	ctyVal, err := utils.MapToCtyValWithSchema(hclData, c.schema)
	if err != nil {
		return nil, err
	}
	return &models.TerraformResourceBlock{
		Labels: []string{c.name, hclBlockName},
		Value:  ctyVal,
	}, nil
}

func flattenCloudRunV2JobLabels(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return tgcresource.RemoveTerraformAttributionLabel(v)
}

func flattenCloudRunV2JobAnnotations(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenCloudRunV2JobClient(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return nil
	}
	if strVal, ok := v.(string); ok && strVal == "" {
		return nil
	}
	return v
}

func flattenCloudRunV2JobClientVersion(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return nil
	}
	if strVal, ok := v.(string); ok && strVal == "" {
		return nil
	}
	return v
}

func flattenCloudRunV2JobLaunchStage(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenCloudRunV2JobBinaryAuthorization(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return nil
	}
	original := v.(map[string]interface{})
	transformed := make(map[string]interface{})
	transformed["breakglass_justification"] =
		flattenCloudRunV2JobBinaryAuthorizationBreakglassJustification(original["breakglassJustification"], d, config)
	transformed["use_default"] =
		flattenCloudRunV2JobBinaryAuthorizationUseDefault(original["useDefault"], d, config)
	transformed["policy"] =
		flattenCloudRunV2JobBinaryAuthorizationPolicy(original["policy"], d, config)
	if tgcresource.AllValuesAreNil(transformed) {
		return nil
	}
	return []interface{}{transformed}
}

func flattenCloudRunV2JobBinaryAuthorizationBreakglassJustification(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return nil
	}
	if strVal, ok := v.(string); ok && strVal == "" {
		return nil
	}
	return v
}

func flattenCloudRunV2JobBinaryAuthorizationUseDefault(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenCloudRunV2JobBinaryAuthorizationPolicy(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return nil
	}
	if strVal, ok := v.(string); ok && strVal == "" {
		return nil
	}
	return v
}

func flattenCloudRunV2JobTemplate(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return nil
	}
	original := v.(map[string]interface{})
	transformed := make(map[string]interface{})
	transformed["labels"] =
		flattenCloudRunV2JobTemplateLabels(original["labels"], d, config)
	transformed["annotations"] =
		flattenCloudRunV2JobTemplateAnnotations(original["annotations"], d, config)
	transformed["parallelism"] =
		flattenCloudRunV2JobTemplateParallelism(original["parallelism"], d, config)
	transformed["task_count"] =
		flattenCloudRunV2JobTemplateTaskCount(original["taskCount"], d, config)
	transformed["template"] =
		flattenCloudRunV2JobTemplateTemplate(original["template"], d, config)
	if tgcresource.AllValuesAreNil(transformed) {
		return nil
	}
	return []interface{}{transformed}
}

func flattenCloudRunV2JobTemplateLabels(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenCloudRunV2JobTemplateAnnotations(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenCloudRunV2JobTemplateParallelism(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	// Handles the string fixed64 format
	if strVal, ok := v.(string); ok {
		if intVal, err := tpgresource.StringToFixed64(strVal); err == nil {
			return intVal
		}
	}

	// number values are represented as float64
	if floatVal, ok := v.(float64); ok {
		intVal := int(floatVal)
		return intVal
	}

	return v // let terraform core handle it otherwise
}

func flattenCloudRunV2JobTemplateTaskCount(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	// Handles the string fixed64 format
	if strVal, ok := v.(string); ok {
		if intVal, err := tpgresource.StringToFixed64(strVal); err == nil {
			return intVal
		}
	}

	// number values are represented as float64
	if floatVal, ok := v.(float64); ok {
		intVal := int(floatVal)
		return intVal
	}

	return v // let terraform core handle it otherwise
}

func flattenCloudRunV2JobTemplateTemplate(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return nil
	}
	original := v.(map[string]interface{})
	transformed := make(map[string]interface{})
	transformed["containers"] =
		flattenCloudRunV2JobTemplateTemplateContainers(original["containers"], d, config)
	transformed["volumes"] =
		flattenCloudRunV2JobTemplateTemplateVolumes(original["volumes"], d, config)
	transformed["timeout"] =
		flattenCloudRunV2JobTemplateTemplateTimeout(original["timeout"], d, config)
	transformed["service_account"] =
		flattenCloudRunV2JobTemplateTemplateServiceAccount(original["serviceAccount"], d, config)
	transformed["execution_environment"] =
		flattenCloudRunV2JobTemplateTemplateExecutionEnvironment(original["executionEnvironment"], d, config)
	transformed["encryption_key"] =
		flattenCloudRunV2JobTemplateTemplateEncryptionKey(original["encryptionKey"], d, config)
	transformed["vpc_access"] =
		flattenCloudRunV2JobTemplateTemplateVpcAccess(original["vpcAccess"], d, config)
	transformed["max_retries"] =
		flattenCloudRunV2JobTemplateTemplateMaxRetries(original["maxRetries"], d, config)
	transformed["node_selector"] =
		flattenCloudRunV2JobTemplateTemplateNodeSelector(original["nodeSelector"], d, config)
	transformed["gpu_zonal_redundancy_disabled"] =
		flattenCloudRunV2JobTemplateTemplateGpuZonalRedundancyDisabled(original["gpuZonalRedundancyDisabled"], d, config)
	if tgcresource.AllValuesAreNil(transformed) {
		return nil
	}
	return []interface{}{transformed}
}

func flattenCloudRunV2JobTemplateTemplateContainers(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return v
	}
	l := v.([]interface{})
	transformed := make([]interface{}, 0, len(l))
	for _, raw := range l {
		original := raw.(map[string]interface{})
		if len(original) < 1 {
			// Do not include empty json objects coming back from the api
			continue
		}
		transformed = append(transformed, map[string]interface{}{
			"name":          flattenCloudRunV2JobTemplateTemplateContainersName(original["name"], d, config),
			"image":         flattenCloudRunV2JobTemplateTemplateContainersImage(original["image"], d, config),
			"command":       flattenCloudRunV2JobTemplateTemplateContainersCommand(original["command"], d, config),
			"args":          flattenCloudRunV2JobTemplateTemplateContainersArgs(original["args"], d, config),
			"env":           flattenCloudRunV2JobTemplateTemplateContainersEnv(original["env"], d, config),
			"resources":     flattenCloudRunV2JobTemplateTemplateContainersResources(original["resources"], d, config),
			"ports":         flattenCloudRunV2JobTemplateTemplateContainersPorts(original["ports"], d, config),
			"volume_mounts": flattenCloudRunV2JobTemplateTemplateContainersVolumeMounts(original["volumeMounts"], d, config),
			"working_dir":   flattenCloudRunV2JobTemplateTemplateContainersWorkingDir(original["workingDir"], d, config),
			"depends_on":    flattenCloudRunV2JobTemplateTemplateContainersDependsOn(original["dependsOn"], d, config),
			"startup_probe": flattenCloudRunV2JobTemplateTemplateContainersStartupProbe(original["startupProbe"], d, config),
		})
	}
	return transformed
}

func flattenCloudRunV2JobTemplateTemplateContainersName(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return nil
	}
	if strVal, ok := v.(string); ok && strVal == "" {
		return nil
	}
	return v
}

func flattenCloudRunV2JobTemplateTemplateContainersImage(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return "unknown"
	}
	transformed := v.(string)
	if transformed == "" {
		return "unknown"
	}
	return v
}

func flattenCloudRunV2JobTemplateTemplateContainersCommand(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenCloudRunV2JobTemplateTemplateContainersArgs(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenCloudRunV2JobTemplateTemplateContainersEnv(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return v
	}
	l := v.([]interface{})
	transformed := schema.NewSet(schema.HashResource(cloudrunv2JobTemplateTemplateContainersContainersEnvSchema()), []interface{}{})
	for _, raw := range l {
		original := raw.(map[string]interface{})
		if len(original) < 1 {
			// Do not include empty json objects coming back from the api
			continue
		}
		transformed.Add(map[string]interface{}{
			"name":         flattenCloudRunV2JobTemplateTemplateContainersEnvName(original["name"], d, config),
			"value":        flattenCloudRunV2JobTemplateTemplateContainersEnvValue(original["value"], d, config),
			"value_source": flattenCloudRunV2JobTemplateTemplateContainersEnvValueSource(original["valueSource"], d, config),
		})
	}
	return transformed
}

func flattenCloudRunV2JobTemplateTemplateContainersEnvName(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return "unknown"
	}
	transformed := v.(string)
	if transformed == "" {
		return "unknown"
	}
	return v
}

func flattenCloudRunV2JobTemplateTemplateContainersEnvValue(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenCloudRunV2JobTemplateTemplateContainersEnvValueSource(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return nil
	}
	original := v.(map[string]interface{})
	transformed := make(map[string]interface{})
	transformed["secret_key_ref"] =
		flattenCloudRunV2JobTemplateTemplateContainersEnvValueSourceSecretKeyRef(original["secretKeyRef"], d, config)
	if tgcresource.AllValuesAreNil(transformed) {
		return nil
	}
	return []interface{}{transformed}
}

func flattenCloudRunV2JobTemplateTemplateContainersEnvValueSourceSecretKeyRef(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return nil
	}
	original := v.(map[string]interface{})
	transformed := make(map[string]interface{})
	transformed["secret"] =
		flattenCloudRunV2JobTemplateTemplateContainersEnvValueSourceSecretKeyRefSecret(original["secret"], d, config)
	transformed["version"] =
		flattenCloudRunV2JobTemplateTemplateContainersEnvValueSourceSecretKeyRefVersion(original["version"], d, config)
	if tgcresource.AllValuesAreNil(transformed) {
		return nil
	}
	return []interface{}{transformed}
}

func flattenCloudRunV2JobTemplateTemplateContainersEnvValueSourceSecretKeyRefSecret(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return "unknown"
	}
	transformed := v.(string)
	if transformed == "" {
		return "unknown"
	}
	return v
}

func flattenCloudRunV2JobTemplateTemplateContainersEnvValueSourceSecretKeyRefVersion(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return "unknown"
	}
	transformed := v.(string)
	if transformed == "" {
		return "unknown"
	}
	return v
}

func flattenCloudRunV2JobTemplateTemplateContainersResources(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return nil
	}
	original := v.(map[string]interface{})
	transformed := make(map[string]interface{})
	transformed["limits"] =
		flattenCloudRunV2JobTemplateTemplateContainersResourcesLimits(original["limits"], d, config)
	if tgcresource.AllValuesAreNil(transformed) {
		return nil
	}
	return []interface{}{transformed}
}

func flattenCloudRunV2JobTemplateTemplateContainersResourcesLimits(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenCloudRunV2JobTemplateTemplateContainersPorts(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return v
	}
	l := v.([]interface{})
	transformed := make([]interface{}, 0, len(l))
	for _, raw := range l {
		original := raw.(map[string]interface{})
		if len(original) < 1 {
			// Do not include empty json objects coming back from the api
			continue
		}
		transformed = append(transformed, map[string]interface{}{
			"name":           flattenCloudRunV2JobTemplateTemplateContainersPortsName(original["name"], d, config),
			"container_port": flattenCloudRunV2JobTemplateTemplateContainersPortsContainerPort(original["containerPort"], d, config),
		})
	}
	return transformed
}

func flattenCloudRunV2JobTemplateTemplateContainersPortsName(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return nil
	}
	if strVal, ok := v.(string); ok && strVal == "" {
		return nil
	}
	return v
}

func flattenCloudRunV2JobTemplateTemplateContainersPortsContainerPort(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	// Handles the string fixed64 format
	if strVal, ok := v.(string); ok {
		if intVal, err := tpgresource.StringToFixed64(strVal); err == nil {
			return intVal
		}
	}

	// number values are represented as float64
	if floatVal, ok := v.(float64); ok {
		intVal := int(floatVal)
		return intVal
	}

	return v // let terraform core handle it otherwise
}

func flattenCloudRunV2JobTemplateTemplateContainersVolumeMounts(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return v
	}
	l := v.([]interface{})
	transformed := make([]interface{}, 0, len(l))
	for _, raw := range l {
		original := raw.(map[string]interface{})
		if len(original) < 1 {
			// Do not include empty json objects coming back from the api
			continue
		}
		transformed = append(transformed, map[string]interface{}{
			"name":       flattenCloudRunV2JobTemplateTemplateContainersVolumeMountsName(original["name"], d, config),
			"mount_path": flattenCloudRunV2JobTemplateTemplateContainersVolumeMountsMountPath(original["mountPath"], d, config),
			"sub_path":   flattenCloudRunV2JobTemplateTemplateContainersVolumeMountsSubPath(original["subPath"], d, config),
		})
	}
	return transformed
}

func flattenCloudRunV2JobTemplateTemplateContainersVolumeMountsName(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return "unknown"
	}
	transformed := v.(string)
	if transformed == "" {
		return "unknown"
	}
	return v
}

func flattenCloudRunV2JobTemplateTemplateContainersVolumeMountsMountPath(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return "unknown"
	}
	transformed := v.(string)
	if transformed == "" {
		return "unknown"
	}
	return v
}

func flattenCloudRunV2JobTemplateTemplateContainersVolumeMountsSubPath(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return nil
	}
	if strVal, ok := v.(string); ok && strVal == "" {
		return nil
	}
	return v
}

func flattenCloudRunV2JobTemplateTemplateContainersWorkingDir(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return nil
	}
	if strVal, ok := v.(string); ok && strVal == "" {
		return nil
	}
	return v
}

func flattenCloudRunV2JobTemplateTemplateContainersDependsOn(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenCloudRunV2JobTemplateTemplateContainersStartupProbe(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return nil
	}
	original := v.(map[string]interface{})
	transformed := make(map[string]interface{})
	transformed["initial_delay_seconds"] =
		flattenCloudRunV2JobTemplateTemplateContainersStartupProbeInitialDelaySeconds(original["initialDelaySeconds"], d, config)
	transformed["timeout_seconds"] =
		flattenCloudRunV2JobTemplateTemplateContainersStartupProbeTimeoutSeconds(original["timeoutSeconds"], d, config)
	transformed["period_seconds"] =
		flattenCloudRunV2JobTemplateTemplateContainersStartupProbePeriodSeconds(original["periodSeconds"], d, config)
	transformed["failure_threshold"] =
		flattenCloudRunV2JobTemplateTemplateContainersStartupProbeFailureThreshold(original["failureThreshold"], d, config)
	transformed["tcp_socket"] =
		flattenCloudRunV2JobTemplateTemplateContainersStartupProbeTcpSocket(original["tcpSocket"], d, config)
	transformed["http_get"] =
		flattenCloudRunV2JobTemplateTemplateContainersStartupProbeHttpGet(original["httpGet"], d, config)
	transformed["grpc"] =
		flattenCloudRunV2JobTemplateTemplateContainersStartupProbeGrpc(original["grpc"], d, config)
	if tgcresource.AllValuesAreNil(transformed) {
		return nil
	}
	return []interface{}{transformed}
}

func flattenCloudRunV2JobTemplateTemplateContainersStartupProbeInitialDelaySeconds(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	// Handles the string fixed64 format
	if strVal, ok := v.(string); ok {
		if intVal, err := tpgresource.StringToFixed64(strVal); err == nil {
			return intVal
		}
	}

	// number values are represented as float64
	if floatVal, ok := v.(float64); ok {
		intVal := int(floatVal)
		return intVal
	}

	return v // let terraform core handle it otherwise
}

func flattenCloudRunV2JobTemplateTemplateContainersStartupProbeTimeoutSeconds(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	// Handles the string fixed64 format
	if strVal, ok := v.(string); ok {
		if intVal, err := tpgresource.StringToFixed64(strVal); err == nil {
			return intVal
		}
	}

	// number values are represented as float64
	if floatVal, ok := v.(float64); ok {
		intVal := int(floatVal)
		return intVal
	}

	return v // let terraform core handle it otherwise
}

func flattenCloudRunV2JobTemplateTemplateContainersStartupProbePeriodSeconds(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	// Handles the string fixed64 format
	if strVal, ok := v.(string); ok {
		if intVal, err := tpgresource.StringToFixed64(strVal); err == nil {
			return intVal
		}
	}

	// number values are represented as float64
	if floatVal, ok := v.(float64); ok {
		intVal := int(floatVal)
		return intVal
	}

	return v // let terraform core handle it otherwise
}

func flattenCloudRunV2JobTemplateTemplateContainersStartupProbeFailureThreshold(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	// Handles the string fixed64 format
	if strVal, ok := v.(string); ok {
		if intVal, err := tpgresource.StringToFixed64(strVal); err == nil {
			return intVal
		}
	}

	// number values are represented as float64
	if floatVal, ok := v.(float64); ok {
		intVal := int(floatVal)
		return intVal
	}

	return v // let terraform core handle it otherwise
}

func flattenCloudRunV2JobTemplateTemplateContainersStartupProbeTcpSocket(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return nil
	}
	original := v.(map[string]interface{})
	transformed := make(map[string]interface{})
	transformed["port"] =
		flattenCloudRunV2JobTemplateTemplateContainersStartupProbeTcpSocketPort(original["port"], d, config)
	return []interface{}{transformed}
}

func flattenCloudRunV2JobTemplateTemplateContainersStartupProbeTcpSocketPort(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	// Handles the string fixed64 format
	if strVal, ok := v.(string); ok {
		if intVal, err := tpgresource.StringToFixed64(strVal); err == nil {
			return intVal
		}
	}

	// number values are represented as float64
	if floatVal, ok := v.(float64); ok {
		intVal := int(floatVal)
		return intVal
	}

	return v // let terraform core handle it otherwise
}

func flattenCloudRunV2JobTemplateTemplateContainersStartupProbeHttpGet(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return nil
	}
	original := v.(map[string]interface{})
	transformed := make(map[string]interface{})
	transformed["path"] =
		flattenCloudRunV2JobTemplateTemplateContainersStartupProbeHttpGetPath(original["path"], d, config)
	transformed["port"] =
		flattenCloudRunV2JobTemplateTemplateContainersStartupProbeHttpGetPort(original["port"], d, config)
	transformed["http_headers"] =
		flattenCloudRunV2JobTemplateTemplateContainersStartupProbeHttpGetHttpHeaders(original["httpHeaders"], d, config)
	return []interface{}{transformed}
}

func flattenCloudRunV2JobTemplateTemplateContainersStartupProbeHttpGetPath(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenCloudRunV2JobTemplateTemplateContainersStartupProbeHttpGetPort(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	// Handles the string fixed64 format
	if strVal, ok := v.(string); ok {
		if intVal, err := tpgresource.StringToFixed64(strVal); err == nil {
			return intVal
		}
	}

	// number values are represented as float64
	if floatVal, ok := v.(float64); ok {
		intVal := int(floatVal)
		return intVal
	}

	return v // let terraform core handle it otherwise
}

func flattenCloudRunV2JobTemplateTemplateContainersStartupProbeHttpGetHttpHeaders(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return v
	}
	l := v.([]interface{})
	transformed := make([]interface{}, 0, len(l))
	for _, raw := range l {
		original := raw.(map[string]interface{})
		if len(original) < 1 {
			// Do not include empty json objects coming back from the api
			continue
		}
		transformed = append(transformed, map[string]interface{}{
			"name":  flattenCloudRunV2JobTemplateTemplateContainersStartupProbeHttpGetHttpHeadersName(original["name"], d, config),
			"value": flattenCloudRunV2JobTemplateTemplateContainersStartupProbeHttpGetHttpHeadersValue(original["value"], d, config),
		})
	}
	return transformed
}

func flattenCloudRunV2JobTemplateTemplateContainersStartupProbeHttpGetHttpHeadersName(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return "unknown"
	}
	transformed := v.(string)
	if transformed == "" {
		return "unknown"
	}
	return v
}

func flattenCloudRunV2JobTemplateTemplateContainersStartupProbeHttpGetHttpHeadersValue(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenCloudRunV2JobTemplateTemplateContainersStartupProbeGrpc(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return nil
	}
	original := v.(map[string]interface{})
	transformed := make(map[string]interface{})
	transformed["port"] =
		flattenCloudRunV2JobTemplateTemplateContainersStartupProbeGrpcPort(original["port"], d, config)
	transformed["service"] =
		flattenCloudRunV2JobTemplateTemplateContainersStartupProbeGrpcService(original["service"], d, config)
	return []interface{}{transformed}
}

func flattenCloudRunV2JobTemplateTemplateContainersStartupProbeGrpcPort(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	// Handles the string fixed64 format
	if strVal, ok := v.(string); ok {
		if intVal, err := tpgresource.StringToFixed64(strVal); err == nil {
			return intVal
		}
	}

	// number values are represented as float64
	if floatVal, ok := v.(float64); ok {
		intVal := int(floatVal)
		return intVal
	}

	return v // let terraform core handle it otherwise
}

func flattenCloudRunV2JobTemplateTemplateContainersStartupProbeGrpcService(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return nil
	}
	if strVal, ok := v.(string); ok && strVal == "" {
		return nil
	}
	return v
}

func flattenCloudRunV2JobTemplateTemplateVolumes(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return v
	}
	l := v.([]interface{})
	transformed := make([]interface{}, 0, len(l))
	for _, raw := range l {
		original := raw.(map[string]interface{})
		if len(original) < 1 {
			// Do not include empty json objects coming back from the api
			continue
		}
		transformed = append(transformed, map[string]interface{}{
			"name":               flattenCloudRunV2JobTemplateTemplateVolumesName(original["name"], d, config),
			"secret":             flattenCloudRunV2JobTemplateTemplateVolumesSecret(original["secret"], d, config),
			"cloud_sql_instance": flattenCloudRunV2JobTemplateTemplateVolumesCloudSqlInstance(original["cloudSqlInstance"], d, config),
			"empty_dir":          flattenCloudRunV2JobTemplateTemplateVolumesEmptyDir(original["emptyDir"], d, config),
			"gcs":                flattenCloudRunV2JobTemplateTemplateVolumesGcs(original["gcs"], d, config),
			"nfs":                flattenCloudRunV2JobTemplateTemplateVolumesNfs(original["nfs"], d, config),
		})
	}
	return transformed
}

func flattenCloudRunV2JobTemplateTemplateVolumesName(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return "unknown"
	}
	transformed := v.(string)
	if transformed == "" {
		return "unknown"
	}
	return v
}

func flattenCloudRunV2JobTemplateTemplateVolumesSecret(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return nil
	}
	original := v.(map[string]interface{})
	transformed := make(map[string]interface{})
	transformed["secret"] =
		flattenCloudRunV2JobTemplateTemplateVolumesSecretSecret(original["secret"], d, config)
	transformed["default_mode"] =
		flattenCloudRunV2JobTemplateTemplateVolumesSecretDefaultMode(original["defaultMode"], d, config)
	transformed["items"] =
		flattenCloudRunV2JobTemplateTemplateVolumesSecretItems(original["items"], d, config)
	if tgcresource.AllValuesAreNil(transformed) {
		return nil
	}
	return []interface{}{transformed}
}

func flattenCloudRunV2JobTemplateTemplateVolumesSecretSecret(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return "unknown"
	}
	transformed := v.(string)
	if transformed == "" {
		return "unknown"
	}
	return v
}

func flattenCloudRunV2JobTemplateTemplateVolumesSecretDefaultMode(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	// Handles the string fixed64 format
	if strVal, ok := v.(string); ok {
		if intVal, err := tpgresource.StringToFixed64(strVal); err == nil {
			return intVal
		}
	}

	// number values are represented as float64
	if floatVal, ok := v.(float64); ok {
		intVal := int(floatVal)
		return intVal
	}

	return v // let terraform core handle it otherwise
}

func flattenCloudRunV2JobTemplateTemplateVolumesSecretItems(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return v
	}
	l := v.([]interface{})
	transformed := make([]interface{}, 0, len(l))
	for _, raw := range l {
		original := raw.(map[string]interface{})
		if len(original) < 1 {
			// Do not include empty json objects coming back from the api
			continue
		}
		transformed = append(transformed, map[string]interface{}{
			"path":    flattenCloudRunV2JobTemplateTemplateVolumesSecretItemsPath(original["path"], d, config),
			"version": flattenCloudRunV2JobTemplateTemplateVolumesSecretItemsVersion(original["version"], d, config),
			"mode":    flattenCloudRunV2JobTemplateTemplateVolumesSecretItemsMode(original["mode"], d, config),
		})
	}
	return transformed
}

func flattenCloudRunV2JobTemplateTemplateVolumesSecretItemsPath(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return "unknown"
	}
	transformed := v.(string)
	if transformed == "" {
		return "unknown"
	}
	return v
}

func flattenCloudRunV2JobTemplateTemplateVolumesSecretItemsVersion(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return "unknown"
	}
	transformed := v.(string)
	if transformed == "" {
		return "unknown"
	}
	return v
}

func flattenCloudRunV2JobTemplateTemplateVolumesSecretItemsMode(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	// Handles the string fixed64 format
	if strVal, ok := v.(string); ok {
		if intVal, err := tpgresource.StringToFixed64(strVal); err == nil {
			return intVal
		}
	}

	// number values are represented as float64
	if floatVal, ok := v.(float64); ok {
		intVal := int(floatVal)
		return intVal
	}

	return v // let terraform core handle it otherwise
}

func flattenCloudRunV2JobTemplateTemplateVolumesCloudSqlInstance(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return nil
	}
	original := v.(map[string]interface{})
	transformed := make(map[string]interface{})
	transformed["instances"] =
		flattenCloudRunV2JobTemplateTemplateVolumesCloudSqlInstanceInstances(original["instances"], d, config)
	if tgcresource.AllValuesAreNil(transformed) {
		return nil
	}
	return []interface{}{transformed}
}

func flattenCloudRunV2JobTemplateTemplateVolumesCloudSqlInstanceInstances(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenCloudRunV2JobTemplateTemplateVolumesEmptyDir(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return nil
	}
	original := v.(map[string]interface{})
	transformed := make(map[string]interface{})
	transformed["medium"] =
		flattenCloudRunV2JobTemplateTemplateVolumesEmptyDirMedium(original["medium"], d, config)
	transformed["size_limit"] =
		flattenCloudRunV2JobTemplateTemplateVolumesEmptyDirSizeLimit(original["sizeLimit"], d, config)
	if tgcresource.AllValuesAreNil(transformed) {
		return nil
	}
	return []interface{}{transformed}
}

func flattenCloudRunV2JobTemplateTemplateVolumesEmptyDirMedium(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenCloudRunV2JobTemplateTemplateVolumesEmptyDirSizeLimit(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return nil
	}
	if strVal, ok := v.(string); ok && strVal == "" {
		return nil
	}
	return v
}

func flattenCloudRunV2JobTemplateTemplateVolumesGcs(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return nil
	}
	original := v.(map[string]interface{})
	transformed := make(map[string]interface{})
	transformed["bucket"] =
		flattenCloudRunV2JobTemplateTemplateVolumesGcsBucket(original["bucket"], d, config)
	transformed["read_only"] =
		flattenCloudRunV2JobTemplateTemplateVolumesGcsReadOnly(original["readOnly"], d, config)
	transformed["mount_options"] =
		flattenCloudRunV2JobTemplateTemplateVolumesGcsMountOptions(original["mountOptions"], d, config)
	if tgcresource.AllValuesAreNil(transformed) {
		return nil
	}
	return []interface{}{transformed}
}

func flattenCloudRunV2JobTemplateTemplateVolumesGcsBucket(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return "unknown"
	}
	transformed := v.(string)
	if transformed == "" {
		return "unknown"
	}
	return v
}

func flattenCloudRunV2JobTemplateTemplateVolumesGcsReadOnly(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenCloudRunV2JobTemplateTemplateVolumesGcsMountOptions(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenCloudRunV2JobTemplateTemplateVolumesNfs(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return nil
	}
	original := v.(map[string]interface{})
	transformed := make(map[string]interface{})
	transformed["server"] =
		flattenCloudRunV2JobTemplateTemplateVolumesNfsServer(original["server"], d, config)
	transformed["path"] =
		flattenCloudRunV2JobTemplateTemplateVolumesNfsPath(original["path"], d, config)
	transformed["read_only"] =
		flattenCloudRunV2JobTemplateTemplateVolumesNfsReadOnly(original["readOnly"], d, config)
	if tgcresource.AllValuesAreNil(transformed) {
		return nil
	}
	return []interface{}{transformed}
}

func flattenCloudRunV2JobTemplateTemplateVolumesNfsServer(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return "unknown"
	}
	transformed := v.(string)
	if transformed == "" {
		return "unknown"
	}
	return v
}

func flattenCloudRunV2JobTemplateTemplateVolumesNfsPath(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return nil
	}
	if strVal, ok := v.(string); ok && strVal == "" {
		return nil
	}
	return v
}

func flattenCloudRunV2JobTemplateTemplateVolumesNfsReadOnly(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenCloudRunV2JobTemplateTemplateTimeout(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenCloudRunV2JobTemplateTemplateServiceAccount(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenCloudRunV2JobTemplateTemplateExecutionEnvironment(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenCloudRunV2JobTemplateTemplateEncryptionKey(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return nil
	}
	if strVal, ok := v.(string); ok && strVal == "" {
		return nil
	}
	return v
}

func flattenCloudRunV2JobTemplateTemplateVpcAccess(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return nil
	}
	original := v.(map[string]interface{})
	transformed := make(map[string]interface{})
	transformed["connector"] =
		flattenCloudRunV2JobTemplateTemplateVpcAccessConnector(original["connector"], d, config)
	transformed["egress"] =
		flattenCloudRunV2JobTemplateTemplateVpcAccessEgress(original["egress"], d, config)
	transformed["network_interfaces"] =
		flattenCloudRunV2JobTemplateTemplateVpcAccessNetworkInterfaces(original["networkInterfaces"], d, config)
	if tgcresource.AllValuesAreNil(transformed) {
		return nil
	}
	return []interface{}{transformed}
}

func flattenCloudRunV2JobTemplateTemplateVpcAccessConnector(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return nil
	}
	if strVal, ok := v.(string); ok && strVal == "" {
		return nil
	}
	return v
}

func flattenCloudRunV2JobTemplateTemplateVpcAccessEgress(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenCloudRunV2JobTemplateTemplateVpcAccessNetworkInterfaces(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return v
	}
	l := v.([]interface{})
	transformed := make([]interface{}, 0, len(l))
	for _, raw := range l {
		original := raw.(map[string]interface{})
		if len(original) < 1 {
			// Do not include empty json objects coming back from the api
			continue
		}
		transformed = append(transformed, map[string]interface{}{
			"network":    flattenCloudRunV2JobTemplateTemplateVpcAccessNetworkInterfacesNetwork(original["network"], d, config),
			"subnetwork": flattenCloudRunV2JobTemplateTemplateVpcAccessNetworkInterfacesSubnetwork(original["subnetwork"], d, config),
			"tags":       flattenCloudRunV2JobTemplateTemplateVpcAccessNetworkInterfacesTags(original["tags"], d, config),
		})
	}
	return transformed
}

func flattenCloudRunV2JobTemplateTemplateVpcAccessNetworkInterfacesNetwork(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenCloudRunV2JobTemplateTemplateVpcAccessNetworkInterfacesSubnetwork(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenCloudRunV2JobTemplateTemplateVpcAccessNetworkInterfacesTags(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenCloudRunV2JobTemplateTemplateMaxRetries(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	// Handles the string fixed64 format
	if strVal, ok := v.(string); ok {
		if intVal, err := tpgresource.StringToFixed64(strVal); err == nil {
			return intVal
		}
	}

	// number values are represented as float64
	if floatVal, ok := v.(float64); ok {
		intVal := int(floatVal)
		return intVal
	}

	return v // let terraform core handle it otherwise
}

func flattenCloudRunV2JobTemplateTemplateNodeSelector(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return nil
	}
	original := v.(map[string]interface{})
	transformed := make(map[string]interface{})
	transformed["accelerator"] =
		flattenCloudRunV2JobTemplateTemplateNodeSelectorAccelerator(original["accelerator"], d, config)
	if tgcresource.AllValuesAreNil(transformed) {
		return nil
	}
	return []interface{}{transformed}
}

func flattenCloudRunV2JobTemplateTemplateNodeSelectorAccelerator(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return "unknown"
	}
	transformed := v.(string)
	if transformed == "" {
		return "unknown"
	}
	return v
}

func flattenCloudRunV2JobTemplateTemplateGpuZonalRedundancyDisabled(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func resourceCloudRunV2JobTgcDecoder(d *schema.ResourceData, meta interface{}, res map[string]interface{}, hclData map[string]interface{}) (map[string]interface{}, map[string]interface{}, error) {
	// Custom decoder for Cloud Run V2 Job to map v1 CAI asset payload (spec.template...)
	// to the Terraform v2 schema structure expected by autogenerated flatteners.
	if res == nil {
		return res, hclData, nil
	}

	// Check if top-level labels/annotations need to be pulled from metadata
	if meta, ok := res["metadata"].(map[string]interface{}); ok {
		if labels, ok := meta["labels"]; ok && res["labels"] == nil {
			res["labels"] = labels
		}
		if annotations, ok := meta["annotations"]; ok && res["annotations"] == nil {
			res["annotations"] = annotations
		}
		if annotationsMap, ok := meta["annotations"].(map[string]interface{}); ok {
			if client, ok := annotationsMap["run.googleapis.com/client-name"]; ok && res["client"] == nil {
				res["client"] = client
			}
			if clientVer, ok := annotationsMap["run.googleapis.com/client-version"]; ok && res["clientVersion"] == nil {
				res["clientVersion"] = clientVer
			}
			if launchStage, ok := annotationsMap["run.googleapis.com/launch-stage"]; ok && res["launchStage"] == nil {
				res["launchStage"] = launchStage
			}
			if bg, ok := annotationsMap["run.googleapis.com/binary-authorization-breakglass"].(string); ok && bg != "" {
				if res["binaryAuthorization"] == nil {
					res["binaryAuthorization"] = make(map[string]interface{})
				}
				if binAuth, ok := res["binaryAuthorization"].(map[string]interface{}); ok {
					binAuth["breakglassJustification"] = bg
				}
			}
			if policy, ok := annotationsMap["run.googleapis.com/binary-authorization"].(string); ok && policy == "default" {
				if res["binaryAuthorization"] == nil {
					res["binaryAuthorization"] = make(map[string]interface{})
				}
				if binAuth, ok := res["binaryAuthorization"].(map[string]interface{}); ok {
					binAuth["useDefault"] = true
				}
			}
		}
	}

	// Map spec.template (v1 execution template) to root template (v2)
	if spec, ok := res["spec"].(map[string]interface{}); ok {
		if binAuth, ok := spec["binaryAuthorization"]; ok && res["binaryAuthorization"] == nil {
			res["binaryAuthorization"] = binAuth
		}
		if execTmpl, ok := spec["template"].(map[string]interface{}); ok {
			v2Tmpl := make(map[string]interface{})
			if execMeta, ok := execTmpl["metadata"].(map[string]interface{}); ok {
				if labels, ok := execMeta["labels"]; ok {
					v2Tmpl["labels"] = labels
				}
				if annotations, ok := execMeta["annotations"]; ok {
					v2Tmpl["annotations"] = annotations
				}
			}
			if execSpec, ok := execTmpl["spec"].(map[string]interface{}); ok {
				if parallelism, ok := execSpec["parallelism"]; ok {
					v2Tmpl["parallelism"] = parallelism
				}
				if taskCount, ok := execSpec["taskCount"]; ok {
					v2Tmpl["taskCount"] = taskCount
				}
				if taskTmpl, ok := execSpec["template"].(map[string]interface{}); ok {
					v2TaskTmpl := make(map[string]interface{})
					var execAnnotations map[string]interface{}
					if execMeta, ok := execTmpl["metadata"].(map[string]interface{}); ok {
						if annotations, ok := execMeta["annotations"].(map[string]interface{}); ok {
							execAnnotations = annotations
							if execEnv, ok := annotations["run.googleapis.com/execution-environment"].(string); ok {
								if execEnv == "gen2" {
									v2TaskTmpl["executionEnvironment"] = "EXECUTION_ENVIRONMENT_GEN2"
								} else if execEnv == "gen1" {
									v2TaskTmpl["executionEnvironment"] = "EXECUTION_ENVIRONMENT_GEN1"
								} else {
									v2TaskTmpl["executionEnvironment"] = execEnv
								}
							}
						}
					}
					if taskSpec, ok := taskTmpl["spec"].(map[string]interface{}); ok {
						if rawContainers, ok := taskSpec["containers"].([]interface{}); ok {
							var v2Containers []interface{}
							for _, rc := range rawContainers {
								if cMap, ok := rc.(map[string]interface{}); ok {
									v2C := make(map[string]interface{})
									for k, v := range cMap {
										v2C[k] = v
									}
									if rawEnvs, ok := cMap["env"].([]interface{}); ok {
										var v2Envs []interface{}
										for _, re := range rawEnvs {
											if eMap, ok := re.(map[string]interface{}); ok {
												v2E := make(map[string]interface{})
												for k, v := range eMap {
													v2E[k] = v
												}
												if vf, ok := eMap["valueFrom"].(map[string]interface{}); ok && v2E["valueSource"] == nil {
													vs := make(map[string]interface{})
													if skr, ok := vf["secretKeyRef"].(map[string]interface{}); ok {
														v2Skr := make(map[string]interface{})
														if name, ok := skr["name"]; ok {
															v2Skr["secret"] = name
														}
														if sec, ok := skr["secret"]; ok {
															v2Skr["secret"] = sec
														}
														if ver, ok := skr["version"]; ok {
															v2Skr["version"] = ver
														}
														if key, ok := skr["key"]; ok {
															v2Skr["version"] = key
														}
														if len(v2Skr) > 0 {
															vs["secretKeyRef"] = v2Skr
														}
													}
													if len(vs) > 0 {
														v2E["valueSource"] = vs
													}
												}
												v2Envs = append(v2Envs, v2E)
											} else {
												v2Envs = append(v2Envs, re)
											}
										}
										v2C["env"] = v2Envs
									}
									v2Containers = append(v2Containers, v2C)
								} else {
									v2Containers = append(v2Containers, rc)
								}
							}
							v2TaskTmpl["containers"] = v2Containers
						}
						if rawVols, ok := taskSpec["volumes"].([]interface{}); ok {
							var v2Vols []interface{}
							for _, rv := range rawVols {
								if volMap, ok := rv.(map[string]interface{}); ok {
									v2Vol := make(map[string]interface{})
									for k, v := range volMap {
										v2Vol[k] = v
									}
									if csi, ok := volMap["csi"].(map[string]interface{}); ok && v2Vol["gcs"] == nil {
										if driver, ok := csi["driver"].(string); ok && driver == "gcsfuse.run.googleapis.com" {
											gcs := make(map[string]interface{})
											if ro, ok := csi["readOnly"]; ok {
												gcs["readOnly"] = ro
											}
											if attrs, ok := csi["volumeAttributes"].(map[string]interface{}); ok {
												if bucket, ok := attrs["bucketName"]; ok {
													gcs["bucket"] = bucket
												}
												if mo, ok := attrs["mountOptions"].(string); ok && mo != "" {
													parts := strings.Split(mo, ",")
													var moList []interface{}
													for _, p := range parts {
														if trimmed := strings.TrimSpace(p); trimmed != "" {
															moList = append(moList, trimmed)
														}
													}
													if len(moList) > 0 {
														gcs["mountOptions"] = moList
													}
												}
											}
											v2Vol["gcs"] = gcs
										}
									}
									if ed, ok := volMap["emptyDir"].(map[string]interface{}); ok {
										if med, ok := ed["medium"].(string); ok {
											if strings.EqualFold(med, "memory") {
												ed["medium"] = "MEMORY"
											} else if strings.EqualFold(med, "disk") {
												ed["medium"] = "DISK"
											} else if strings.ToUpper(med) == "MEMORY" || strings.ToUpper(med) == "DISK" {
												ed["medium"] = strings.ToUpper(med)
											}
										}
										v2Vol["emptyDir"] = ed
									}
									v2Vols = append(v2Vols, v2Vol)
								} else {
									v2Vols = append(v2Vols, rv)
								}
							}
							v2TaskTmpl["volumes"] = v2Vols
						}
						if timeoutVal, ok := taskSpec["timeoutSeconds"]; ok {
							if timeoutStr, ok := timeoutVal.(string); ok {
								if !strings.HasSuffix(timeoutStr, "s") {
									v2TaskTmpl["timeout"] = timeoutStr + "s"
								} else {
									v2TaskTmpl["timeout"] = timeoutStr
								}
							} else if timeoutNum, ok := timeoutVal.(float64); ok {
								v2TaskTmpl["timeout"] = fmt.Sprintf("%ds", int(timeoutNum))
							} else if timeoutInt, ok := timeoutVal.(int); ok {
								v2TaskTmpl["timeout"] = fmt.Sprintf("%ds", timeoutInt)
							} else {
								v2TaskTmpl["timeout"] = timeoutVal
							}
						}
						if sa, ok := taskSpec["serviceAccountName"]; ok {
							v2TaskTmpl["serviceAccount"] = sa
						}
						if retries, ok := taskSpec["maxRetries"]; ok {
							v2TaskTmpl["maxRetries"] = retries
						}
						vpc := make(map[string]interface{})
						if existingVpc, ok := taskSpec["vpcAccess"].(map[string]interface{}); ok {
							for k, v := range existingVpc {
								vpc[k] = v
							}
						}
						if execAnnotations != nil {
							if connector, ok := execAnnotations["run.googleapis.com/vpc-access-connector"].(string); ok && connector != "" {
								vpc["connector"] = connector
							}
							if egress, ok := execAnnotations["run.googleapis.com/vpc-access-egress"].(string); ok && egress != "" {
								vpc["egress"] = egress
							}
							if niStr, ok := execAnnotations["run.googleapis.com/network-interfaces"].(string); ok && niStr != "" {
								var nis []map[string]interface{}
								if err := json.Unmarshal([]byte(niStr), &nis); err == nil {
									var v2Nis []interface{}
									for _, ni := range nis {
										v2Ni := make(map[string]interface{})
										if net, ok := ni["network"]; ok {
											v2Ni["network"] = net
										}
										if subnet, ok := ni["subnetwork"]; ok {
											v2Ni["subnetwork"] = subnet
										}
										if tags, ok := ni["tags"]; ok {
											v2Ni["tags"] = tags
										}
										v2Nis = append(v2Nis, v2Ni)
									}
									if len(v2Nis) > 0 {
										vpc["networkInterfaces"] = v2Nis
									}
								}
							}
						}
						if eg, ok := vpc["egress"].(string); ok && eg != "" {
							if strings.EqualFold(eg, "all-traffic") || strings.EqualFold(eg, "all_traffic") {
								vpc["egress"] = "ALL_TRAFFIC"
							} else if strings.EqualFold(eg, "private-ranges-only") || strings.EqualFold(eg, "private_ranges_only") {
								vpc["egress"] = "PRIVATE_RANGES_ONLY"
							} else {
								vpc["egress"] = strings.ToUpper(strings.ReplaceAll(eg, "-", "_"))
							}
						}
						var sqlInstsStr string
						if execAnnotations != nil {
							if s, ok := execAnnotations["run.googleapis.com/cloudsql-instances"].(string); ok {
								sqlInstsStr = s
							}
						}
						if sqlInstsStr == "" {
							if topMeta, ok := res["metadata"].(map[string]interface{}); ok {
								if ann, ok := topMeta["annotations"].(map[string]interface{}); ok {
									if s, ok := ann["run.googleapis.com/cloudsql-instances"].(string); ok {
										sqlInstsStr = s
									}
								}
							}
						}
						if sqlInstsStr != "" {
							parts := strings.Split(sqlInstsStr, ",")
							var instList []interface{}
							for _, p := range parts {
								if trimmed := strings.TrimSpace(p); trimmed != "" {
									instList = append(instList, trimmed)
								}
							}
							if len(instList) > 0 {
								hasSqlVol := false
								if vols, ok := v2TaskTmpl["volumes"].([]interface{}); ok {
									for _, v := range vols {
										if vMap, ok := v.(map[string]interface{}); ok {
											if name, ok := vMap["name"].(string); ok && name == "cloudsql" {
												hasSqlVol = true
												break
											}
										}
									}
								}
								if !hasSqlVol {
									sqlVol := map[string]interface{}{
										"name": "cloudsql",
										"cloudSqlInstance": map[string]interface{}{
											"instances": instList,
										},
									}
									if vols, ok := v2TaskTmpl["volumes"].([]interface{}); ok {
										v2TaskTmpl["volumes"] = append(vols, sqlVol)
									} else {
										v2TaskTmpl["volumes"] = []interface{}{sqlVol}
									}
								}
								if cs, ok := v2TaskTmpl["containers"].([]interface{}); ok {
									for i, c := range cs {
										if cMap, ok := c.(map[string]interface{}); ok {
											hasSqlMount := false
											if vms, ok := cMap["volumeMounts"].([]interface{}); ok {
												for _, vm := range vms {
													if vmMap, ok := vm.(map[string]interface{}); ok {
														if name, ok := vmMap["name"].(string); ok && name == "cloudsql" {
															hasSqlMount = true
															break
														}
													}
												}
											}
											if !hasSqlMount {
												sqlMount := map[string]interface{}{
													"name":      "cloudsql",
													"mountPath": "/cloudsql",
												}
												if vms, ok := cMap["volumeMounts"].([]interface{}); ok {
													cMap["volumeMounts"] = append(vms, sqlMount)
												} else {
													cMap["volumeMounts"] = []interface{}{sqlMount}
												}
											}
											cs[i] = cMap
										}
									}
									v2TaskTmpl["containers"] = cs
								}
							}
						}
						if len(vpc) > 0 {
							v2TaskTmpl["vpcAccess"] = vpc
						}
						if ns, ok := taskSpec["nodeSelector"]; ok {
							v2TaskTmpl["nodeSelector"] = ns
						}
						if ek, ok := taskSpec["encryptionKey"]; ok {
							v2TaskTmpl["encryptionKey"] = ek
						}
						if gpu, ok := taskSpec["gpuZonalRedundancyDisabled"]; ok {
							v2TaskTmpl["gpuZonalRedundancyDisabled"] = gpu
						}
					}
					v2Tmpl["template"] = v2TaskTmpl
				}
			}
			res["template"] = v2Tmpl
		}
	}

	return res, hclData, nil
}
