// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package netapp_test

import (
	"os"
	"testing"

	"github.com/GoogleCloudPlatform/terraform-google-conversion/v7/test"
)

func TestAccNetappVolumeReplication(t *testing.T) {
	if os.Getenv("WRITE_FILES") != "" {
		t.Parallel()
	}
	tests := []test.TestCase{
		{
			Name: "TestAccNetappVolumeReplication_netappVolumeReplicationCreateExample",
		},
		{
			Name: "TestAccNetappVolumeReplication_NetappVolumeReplicationCreateExample_update",
		},
	}

	for _, tt := range tests {
		tt := tt

		t.Run(tt.Name, func(t *testing.T) {
			t.Parallel()

			if tt.Skip != "" {
				t.Skipf("Skipping %s test case: This case is currently disabled due to Issue.", tt.Name)
			}

			test.BidirectionalConversion(
				t,
				[]string{
					"count",
					"delete_destination_volume",
					"depends_on",
					"destination_volume_parameters",
					"for_each",
					"force_stopping",
					"lifecycle",
					"location",
					"name",
					"provider",
					"replication_enabled",
					"timeouts",
					"volume_name",
					"wait_for_mirror",
					// DEBUG WriteOnly properties:
					// state - WriteOnly=false - IgnoreRead=false
					// stateDetails - WriteOnly=false - IgnoreRead=false
					// role - WriteOnly=false - IgnoreRead=false
					// replicationSchedule - WriteOnly=false - IgnoreRead=false
					// mirrorState - WriteOnly=false - IgnoreRead=false
					// createTime - WriteOnly=false - IgnoreRead=false
					// destinationVolume - WriteOnly=false - IgnoreRead=false
					// transferStats - WriteOnly=false - IgnoreRead=false
					// labels - WriteOnly=false - IgnoreRead=false
					// destinationVolumeParameters - WriteOnly=false - IgnoreRead=true
					// sourceVolume - WriteOnly=false - IgnoreRead=false
					// healthy - WriteOnly=false - IgnoreRead=false
					// description - WriteOnly=false - IgnoreRead=false
					// hybridReplicationType - WriteOnly=false - IgnoreRead=false
					// hybridPeeringDetails - WriteOnly=false - IgnoreRead=false
					// hybridReplicationUserCommands - WriteOnly=false - IgnoreRead=false
					// terraformLabels - WriteOnly=false - IgnoreRead=false
					// effectiveLabels - WriteOnly=false - IgnoreRead=false
					// location - WriteOnly=false - IgnoreRead=false
					// volumeName - WriteOnly=false - IgnoreRead=false
					// name - WriteOnly=false - IgnoreRead=false
					// storagePool - WriteOnly=false - IgnoreRead=false
					// volumeId - WriteOnly=false - IgnoreRead=false
					// shareName - WriteOnly=false - IgnoreRead=false
					// description - WriteOnly=false - IgnoreRead=false
					// tieringPolicy - WriteOnly=false - IgnoreRead=false
					// coolingThresholdDays - WriteOnly=false - IgnoreRead=false
					// tierAction - WriteOnly=false - IgnoreRead=false
				},
				"google_netapp_volume_replication",
			)
		})
	}
}
