// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package compute_test

import (
	"os"
	"testing"

	"github.com/GoogleCloudPlatform/terraform-google-conversion/v7/test"
)

func TestAccComputeTargetHttpsProxy(t *testing.T) {
	if os.Getenv("WRITE_FILES") != "" {
		t.Parallel()
	}
	tests := []test.TestCase{
		{
			Name: "TestAccComputeTargetHttpsProxy_targetHttpsProxyBasicExample",
		},
		{
			Name: "TestAccComputeTargetHttpsProxy_targetHttpsProxyHttpKeepAliveTimeoutExample",
		},
		{
			Name: "TestAccComputeTargetHttpsProxy_targetHttpsProxyCertificateManagerCertificateExample",
		},
		{
			Name: "TestAccComputeTargetHttpsProxy_targetHttpsProxyFingerprintExample",
		},
		{
			Name: "TestAccComputeTargetHttpsProxy_update",
		},
		{
			Name: "TestAccComputeTargetHttpsProxy_certificateMap",
		},
		{
			Name: "TestAccComputeTargetHttpsProxyServerTlsPolicy_update",
		},
	}

	for _, tt := range tests {
		tt := tt

		t.Run(tt.Name, func(t *testing.T) {
			t.Parallel()

			if tt.Skip != "" {
				t.Skipf("Skipping %s test case: This case is currently disabled due to Issue.", tt.Name)
			}

			test.BidirectionalConversion(
				t,
				[]string{
					"count",
					"depends_on",
					"for_each",
					"lifecycle",
					"provider",
					"timeouts",
					// DEBUG WriteOnly properties:
					// creationTimestamp - WriteOnly=false - IgnoreRead=false
					// description - WriteOnly=false - IgnoreRead=false
					// proxyId - WriteOnly=false - IgnoreRead=false
					// name - WriteOnly=false - IgnoreRead=false
					// quicOverride - WriteOnly=false - IgnoreRead=false
					// tlsEarlyData - WriteOnly=false - IgnoreRead=false
					// certificateManagerCertificates - WriteOnly=false - IgnoreRead=false
					// sslCertificates - WriteOnly=false - IgnoreRead=false
					// certificateMap - WriteOnly=false - IgnoreRead=false
					// sslPolicy - WriteOnly=false - IgnoreRead=false
					// urlMap - WriteOnly=false - IgnoreRead=false
					// proxyBind - WriteOnly=false - IgnoreRead=false
					// httpKeepAliveTimeoutSec - WriteOnly=false - IgnoreRead=false
					// serverTlsPolicy - WriteOnly=false - IgnoreRead=false
					// fingerprint - WriteOnly=false - IgnoreRead=false
				},
				"google_compute_target_https_proxy",
			)
		})
	}
}
