// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package compute_test

import (
	"os"
	"testing"

	"github.com/GoogleCloudPlatform/terraform-google-conversion/v7/test"
)

func TestAccComputeNodeTemplate(t *testing.T) {
	if os.Getenv("WRITE_FILES") != "" {
		t.Parallel()
	}
	tests := []test.TestCase{
		{
			Name: "TestAccComputeNodeTemplate_nodeTemplateBasicExample",
		},
		{
			Name: "TestAccComputeNodeTemplate_nodeTemplateServerBindingExample",
		},
		{
			Name: "TestAccComputeNodeTemplate_nodeTemplateAcceleratorsExample",
		},
		{
			Name: "TestAccComputeNodeTemplate_nodeTemplateDisksExample",
		},
	}

	for _, tt := range tests {
		tt := tt

		t.Run(tt.Name, func(t *testing.T) {
			t.Parallel()

			if tt.Skip != "" {
				t.Skipf("Skipping %s test case: This case is currently disabled due to Issue.", tt.Name)
			}

			test.BidirectionalConversion(
				t,
				[]string{
					"count",
					"depends_on",
					"for_each",
					"lifecycle",
					"provider",
					"timeouts",
					// DEBUG WriteOnly properties:
					// creationTimestamp - WriteOnly=false - IgnoreRead=false
					// description - WriteOnly=false - IgnoreRead=false
					// name - WriteOnly=false - IgnoreRead=false
					// nodeAffinityLabels - WriteOnly=false - IgnoreRead=false
					// nodeType - WriteOnly=false - IgnoreRead=false
					// nodeTypeFlexibility - WriteOnly=false - IgnoreRead=false
					// serverBinding - WriteOnly=false - IgnoreRead=false
					// accelerators - WriteOnly=false - IgnoreRead=false
					// cpuOvercommitType - WriteOnly=false - IgnoreRead=false
					// disks - WriteOnly=false - IgnoreRead=false
					// region - WriteOnly=false - IgnoreRead=false
					// cpus - WriteOnly=false - IgnoreRead=false
					// memory - WriteOnly=false - IgnoreRead=false
					// type - WriteOnly=false - IgnoreRead=false
					// acceleratorCount - WriteOnly=false - IgnoreRead=false
					// acceleratorType - WriteOnly=false - IgnoreRead=false
					// diskCount - WriteOnly=false - IgnoreRead=false
					// diskType - WriteOnly=false - IgnoreRead=false
					// diskSizeGb - WriteOnly=false - IgnoreRead=false
				},
				"google_compute_node_template",
			)
		})
	}
}
