// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package compute_test

import (
	"os"
	"testing"

	"github.com/GoogleCloudPlatform/terraform-google-conversion/v7/test"
)

func TestAccComputeRegionHealthCheck(t *testing.T) {
	if os.Getenv("WRITE_FILES") != "" {
		t.Parallel()
	}
	tests := []test.TestCase{
		{
			Name: "TestAccComputeRegionHealthCheck_typeTransition",
			Skip: "Test data has mismatched steps",
		},
		{
			Name: "TestAccComputeRegionHealthCheck_grpcWithTls_create",
			Skip: "grpcTlsHealthCheck is not in CAI asset, but is required in this test.",
		},
		{
			Name: "TestAccComputeRegionHealthCheck_grpcWithTls_update",
			Skip: "grpcTlsHealthCheck is not in CAI asset, but is required in this test.",
		},
		{
			Name: "TestAccComputeRegionHealthCheck_regionHealthCheckTcpExample",
		},
		{
			Name: "TestAccComputeRegionHealthCheck_regionHealthCheckTcpFullExample",
		},
		{
			Name: "TestAccComputeRegionHealthCheck_regionHealthCheckSslExample",
		},
		{
			Name: "TestAccComputeRegionHealthCheck_regionHealthCheckSslFullExample",
		},
		{
			Name: "TestAccComputeRegionHealthCheck_regionHealthCheckHttpExample",
		},
		{
			Name: "TestAccComputeRegionHealthCheck_regionHealthCheckHttpFullExample",
		},
		{
			Name: "TestAccComputeRegionHealthCheck_regionHealthCheckHttpsExample",
		},
		{
			Name: "TestAccComputeRegionHealthCheck_regionHealthCheckHttpsFullExample",
		},
		{
			Name: "TestAccComputeRegionHealthCheck_regionHealthCheckHttp2Example",
		},
		{
			Name: "TestAccComputeRegionHealthCheck_regionHealthCheckHttp2FullExample",
		},
		{
			Name: "TestAccComputeRegionHealthCheck_regionHealthCheckGrpcExample",
		},
		{
			Name: "TestAccComputeRegionHealthCheck_regionHealthCheckGrpcFullExample",
		},
		{
			Name: "TestAccComputeRegionHealthCheck_regionHealthCheckGrpcWithTlsExample",
			Skip: "grpcTlsHealthCheck is not in CAI asset, but is required in this test.",
		},
		{
			Name: "TestAccComputeRegionHealthCheck_regionHealthCheckGrpcWithTlsFullExample",
			Skip: "grpcTlsHealthCheck is not in CAI asset, but is required in this test.",
		},
		{
			Name: "TestAccComputeRegionHealthCheck_tcp_update",
		},
		{
			Name: "TestAccComputeRegionHealthCheck_ssl_port_spec",
		},
		{
			Name: "TestAccComputeRegionHealthCheck_http_port_spec",
		},
		{
			Name: "TestAccComputeRegionHealthCheck_https_serving_port",
		},
		{
			Name: "TestAccComputeRegionHealthCheck_logConfigDisabled",
		},
	}

	for _, tt := range tests {
		tt := tt

		t.Run(tt.Name, func(t *testing.T) {
			t.Parallel()

			if tt.Skip != "" {
				t.Skipf("Skipping %s test case: This case is currently disabled due to Issue.", tt.Name)
			}

			test.BidirectionalConversion(
				t,
				[]string{
					"count",
					"depends_on",
					"for_each",
					"grpc_tls_health_check",
					"lifecycle",
					"provider",
					"timeouts",
					// DEBUG WriteOnly properties:
					// checkIntervalSec - WriteOnly=false - IgnoreRead=false
					// creationTimestamp - WriteOnly=false - IgnoreRead=false
					// description - WriteOnly=false - IgnoreRead=false
					// healthCheckId - WriteOnly=false - IgnoreRead=false
					// healthyThreshold - WriteOnly=false - IgnoreRead=false
					// name - WriteOnly=false - IgnoreRead=false
					// unhealthyThreshold - WriteOnly=false - IgnoreRead=false
					// timeoutSec - WriteOnly=false - IgnoreRead=false
					// type - WriteOnly=false - IgnoreRead=false
					// httpHealthCheck - WriteOnly=false - IgnoreRead=false
					// httpsHealthCheck - WriteOnly=false - IgnoreRead=false
					// tcpHealthCheck - WriteOnly=false - IgnoreRead=false
					// sslHealthCheck - WriteOnly=false - IgnoreRead=false
					// http2HealthCheck - WriteOnly=false - IgnoreRead=false
					// grpcHealthCheck - WriteOnly=false - IgnoreRead=false
					// grpcTlsHealthCheck - WriteOnly=false - IgnoreRead=false
					// logConfig - WriteOnly=false - IgnoreRead=false
					// region - WriteOnly=false - IgnoreRead=false
					// host - WriteOnly=false - IgnoreRead=false
					// requestPath - WriteOnly=false - IgnoreRead=false
					// response - WriteOnly=false - IgnoreRead=false
					// port - WriteOnly=false - IgnoreRead=false
					// portName - WriteOnly=false - IgnoreRead=false
					// proxyHeader - WriteOnly=false - IgnoreRead=false
					// portSpecification - WriteOnly=false - IgnoreRead=false
					// host - WriteOnly=false - IgnoreRead=false
					// requestPath - WriteOnly=false - IgnoreRead=false
					// response - WriteOnly=false - IgnoreRead=false
					// port - WriteOnly=false - IgnoreRead=false
					// portName - WriteOnly=false - IgnoreRead=false
					// proxyHeader - WriteOnly=false - IgnoreRead=false
					// portSpecification - WriteOnly=false - IgnoreRead=false
					// request - WriteOnly=false - IgnoreRead=false
					// response - WriteOnly=false - IgnoreRead=false
					// port - WriteOnly=false - IgnoreRead=false
					// portName - WriteOnly=false - IgnoreRead=false
					// proxyHeader - WriteOnly=false - IgnoreRead=false
					// portSpecification - WriteOnly=false - IgnoreRead=false
					// request - WriteOnly=false - IgnoreRead=false
					// response - WriteOnly=false - IgnoreRead=false
					// port - WriteOnly=false - IgnoreRead=false
					// portName - WriteOnly=false - IgnoreRead=false
					// proxyHeader - WriteOnly=false - IgnoreRead=false
					// portSpecification - WriteOnly=false - IgnoreRead=false
					// host - WriteOnly=false - IgnoreRead=false
					// requestPath - WriteOnly=false - IgnoreRead=false
					// response - WriteOnly=false - IgnoreRead=false
					// port - WriteOnly=false - IgnoreRead=false
					// portName - WriteOnly=false - IgnoreRead=false
					// proxyHeader - WriteOnly=false - IgnoreRead=false
					// portSpecification - WriteOnly=false - IgnoreRead=false
					// port - WriteOnly=false - IgnoreRead=false
					// portName - WriteOnly=false - IgnoreRead=false
					// portSpecification - WriteOnly=false - IgnoreRead=false
					// grpcServiceName - WriteOnly=false - IgnoreRead=false
					// port - WriteOnly=false - IgnoreRead=false
					// portSpecification - WriteOnly=false - IgnoreRead=false
					// grpcServiceName - WriteOnly=false - IgnoreRead=false
					// enable - WriteOnly=false - IgnoreRead=false
				},
				"google_compute_region_health_check",
			)
		})
	}
}
