// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This code is generated by Magic Modules using the following:
//
//     Configuration: https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/products/kms/AutokeyConfig.yaml
//     Template:      https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/tgc_next/services/resource.go.tmpl
//
//     DO NOT EDIT this file directly. Any changes made to this file will be
//     overwritten during the next generation cycle.
//
// ----------------------------------------------------------------------------

package kms

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"log"
	"reflect"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/structure"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"

	"github.com/GoogleCloudPlatform/terraform-google-conversion/v7/pkg/tgcresource"
	"github.com/GoogleCloudPlatform/terraform-google-conversion/v7/pkg/tpgresource"
	transport_tpg "github.com/GoogleCloudPlatform/terraform-google-conversion/v7/pkg/transport"
	"github.com/GoogleCloudPlatform/terraform-google-conversion/v7/pkg/verify"
)

const (
	autokeyFolderPrefix  = "folders/"
	autokeyProjectPrefix = "projects/"
	autokeyConfigSuffix  = "/autokeyConfig"
)

func autokeyHasPrefix(value, prefix string) bool {
	return len(value) >= len(prefix) && value[:len(prefix)] == prefix
}

func autokeyTrimPrefix(value, prefix string) string {
	if autokeyHasPrefix(value, prefix) {
		return value[len(prefix):]
	}
	return value
}

func autokeyTrimSuffix(value, suffix string) string {
	if len(value) >= len(suffix) && value[len(value)-len(suffix):] == suffix {
		return value[:len(value)-len(suffix)]
	}
	return value
}

func autokeyJoin(fields []string) string {
	result := ""
	for i, field := range fields {
		if i > 0 {
			result += ","
		}
		result += field
	}
	return result
}

func normalizeParent(parent, kind string) string {
	if parent == "" {
		return parent
	}
	switch kind {
	case "folder":
		if !autokeyHasPrefix(parent, autokeyFolderPrefix) {
			return autokeyFolderPrefix + parent
		}
	case "project":
		if !autokeyHasPrefix(parent, autokeyProjectPrefix) {
			return autokeyProjectPrefix + parent
		}
	}
	return parent
}

func folderPrefixSuppress(k, old, new string, d *schema.ResourceData) bool {
	return autokeyTrimPrefix(old, autokeyFolderPrefix) == autokeyTrimPrefix(new, autokeyFolderPrefix)
}
func projectPrefixSuppress(k, old, new string, d *schema.ResourceData) bool {
	return autokeyTrimPrefix(old, autokeyProjectPrefix) == autokeyTrimPrefix(new, autokeyProjectPrefix)
}

var (
	_ = bytes.Clone
	_ = context.WithCancel
	_ = fmt.Sprintf
	_ = json.Unmarshal
	_ = log.Print
	_ = reflect.ValueOf
	_ = regexp.Match
	_ = sort.IntSlice{}
	_ = strconv.Atoi
	_ = strings.Trim
	_ = schema.Noop
	_ = structure.NormalizeJsonString
	_ = validation.All
	_ = tgcresource.RemoveTerraformAttributionLabel
	_ = tpgresource.GetRegion
	_ = transport_tpg.Config{}
	_ = verify.ProjectRegex
)

const KMSAutokeyConfigAssetType string = "cloudkms.googleapis.com/AutokeyConfig"

const KMSAutokeyConfigSchemaName string = "google_kms_autokey_config"

func ResourceKMSAutokeyConfig() *schema.Resource {
	return &schema.Resource{
		Schema: map[string]*schema.Schema{
			"folder": {
				Type:             schema.TypeString,
				Optional:         true,
				ForceNew:         true,
				DiffSuppressFunc: folderPrefixSuppress,
				Description:      `The folder for which to retrieve config.`,
				ConflictsWith:    []string{},
			},
			"key_project": {
				Type:     schema.TypeString,
				Optional: true,
				Description: `The target key project for a given folder where KMS Autokey will provision a
CryptoKey for any new KeyHandle the Developer creates. Should have the form
'projects/<project_id_or_number>'.`,
			},
			"key_project_resolution_mode": {
				Type:         schema.TypeString,
				Optional:     true,
				ValidateFunc: verify.ValidateEnum([]string{"KEY_PROJECT_RESOLUTION_MODE_UNSPECIFIED", "DEDICATED_KEY_PROJECT", "RESOURCE_PROJECT", "DISABLED", ""}),
				Description:  `How Autokey determines which project to use when provisioning CMEK keys. Possible values: ["KEY_PROJECT_RESOLUTION_MODE_UNSPECIFIED", "DEDICATED_KEY_PROJECT", "RESOURCE_PROJECT", "DISABLED"]`,
			},
			"project": {
				Type:             schema.TypeString,
				Optional:         true,
				ForceNew:         true,
				DiffSuppressFunc: projectPrefixSuppress,
				Description:      `The project for which to retrieve config.`,
				ConflictsWith:    []string{},
			},
			"etag": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: `The etag of the AutokeyConfig for optimistic concurrency control.`,
			},
			"name": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: `The resource name for the 'AutokeyConfig' in the format 'folders/{{folder_id}}/autokeyConfig' or 'projects/{{project_id}}/autokeyConfig'.`,
			},
		},
		UseJSONNumber: true,
	}
}
