// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package documentaiwarehouse

import (
	"fmt"

	"github.com/GoogleCloudPlatform/terraform-google-conversion/v2/cai2hcl/common"
	"github.com/GoogleCloudPlatform/terraform-google-conversion/v2/caiasset"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	transport_tpg "github.com/hashicorp/terraform-provider-google-beta/google-beta/transport"
)

const DocumentAIWarehouseLocationAssetType string = "contentwarehouse.googleapis.com/Location"

const DocumentAIWarehouseLocationAssetNameRegex string = "projects/(?P<project_number>[^/]+)/locations/(?P<location>[^/]+):initialize"

type DocumentAIWarehouseLocationConverter struct {
	name   string
	schema map[string]*schema.Schema
}

func NewDocumentAIWarehouseLocationConverter(name string, schema map[string]*schema.Schema) common.Converter {
	return &DocumentAIWarehouseLocationConverter{
		name:   name,
		schema: schema,
	}
}

func (c *DocumentAIWarehouseLocationConverter) Convert(assets []*caiasset.Asset) ([]*common.HCLResourceBlock, error) {
	var blocks []*common.HCLResourceBlock
	config := common.NewConfig()

	for _, asset := range assets {
		if asset == nil {
			continue
		}
		if asset.Resource != nil && asset.Resource.Data != nil {
			block, err := c.convertResourceData(asset, config)
			if err != nil {
				return nil, err
			}
			blocks = append(blocks, block)
		}
	}
	return blocks, nil
}

func (c *DocumentAIWarehouseLocationConverter) convertResourceData(asset *caiasset.Asset, config *transport_tpg.Config) (*common.HCLResourceBlock, error) {
	if asset == nil || asset.Resource == nil || asset.Resource.Data == nil {
		return nil, fmt.Errorf("asset resource data is nil")
	}

	assetResourceData := asset.Resource.Data

	hcl, _ := resourceDocumentAIWarehouseLocationRead(assetResourceData, config)

	ctyVal, err := common.MapToCtyValWithSchema(hcl, c.schema)
	if err != nil {
		return nil, err
	}

	resourceName := assetResourceData["name"].(string)

	return &common.HCLResourceBlock{
		Labels: []string{c.name, resourceName},
		Value:  ctyVal,
	}, nil
}

func resourceDocumentAIWarehouseLocationRead(resource map[string]interface{}, config *transport_tpg.Config) (map[string]interface{}, error) {
	result := make(map[string]interface{})
	var resource_data *schema.ResourceData = nil

	result["database_type"] = flattenDocumentAIWarehouseLocationDatabaseType(resource["databaseType"], resource_data, config)
	result["access_control_mode"] = flattenDocumentAIWarehouseLocationAccessControlMode(resource["accessControlMode"], resource_data, config)
	result["kms_key"] = flattenDocumentAIWarehouseLocationKmsKey(resource["kmsKey"], resource_data, config)
	result["document_creator_default_role"] = flattenDocumentAIWarehouseLocationDocumentCreatorDefaultRole(resource["documentCreatorDefaultRole"], resource_data, config)

	return result, nil
}

func flattenDocumentAIWarehouseLocationDatabaseType(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenDocumentAIWarehouseLocationAccessControlMode(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenDocumentAIWarehouseLocationKmsKey(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenDocumentAIWarehouseLocationDocumentCreatorDefaultRole(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}
