// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package cloudasset_test

import (
	"os"
	"testing"

	"github.com/GoogleCloudPlatform/terraform-google-conversion/v7/test"
)

func TestAccCloudAssetOrganizationFeed(t *testing.T) {
	if os.Getenv("WRITE_FILES") != "" {
		t.Parallel()
	}
	tests := []test.TestCase{
		{
			Name: "TestAccCloudAssetOrganizationFeed_cloudAssetOrganizationFeedExample",
		},
	}

	for _, tt := range tests {
		tt := tt

		t.Run(tt.Name, func(t *testing.T) {
			t.Parallel()

			if tt.Skip != "" {
				t.Skipf("Skipping %s test case: This case is currently disabled due to Issue.", tt.Name)
			}

			test.BidirectionalConversion(
				t,
				[]string{
					"billing_project",
					"count",
					"depends_on",
					"feed_id",
					"for_each",
					"lifecycle",
					"org_id",
					"provider",
					"timeouts",
					// DEBUG WriteOnly properties:
					// billing_project - WriteOnly=false - IgnoreRead=false
					// name - WriteOnly=false - IgnoreRead=false
					// feedId - WriteOnly=false - IgnoreRead=false
					// assetNames - WriteOnly=false - IgnoreRead=false
					// assetTypes - WriteOnly=false - IgnoreRead=false
					// contentType - WriteOnly=false - IgnoreRead=false
					// feedOutputConfig - WriteOnly=false - IgnoreRead=false
					// condition - WriteOnly=false - IgnoreRead=false
					// org_id - WriteOnly=false - IgnoreRead=false
					// pubsubDestination - WriteOnly=false - IgnoreRead=false
					// topic - WriteOnly=false - IgnoreRead=false
					// expression - WriteOnly=false - IgnoreRead=false
					// title - WriteOnly=false - IgnoreRead=false
					// description - WriteOnly=false - IgnoreRead=false
					// location - WriteOnly=false - IgnoreRead=false
				},
				"google_cloud_asset_organization_feed",
			)
		})
	}
}
