// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package developerconnect_test

import (
	"os"
	"testing"

	"github.com/GoogleCloudPlatform/terraform-google-conversion/v7/test"
)

func TestAccDeveloperConnectGitRepositoryLink(t *testing.T) {
	if os.Getenv("WRITE_FILES") != "" {
		t.Parallel()
	}
	tests := []test.TestCase{
		{
			Name: "TestAccDeveloperConnectGitRepositoryLink_developerConnectGitRepositoryLinkGithubExample",
		},
	}

	for _, tt := range tests {
		tt := tt

		t.Run(tt.Name, func(t *testing.T) {
			t.Parallel()

			if tt.Skip != "" {
				t.Skipf("Skipping %s test case: This case is currently disabled due to Issue.", tt.Name)
			}

			test.BidirectionalConversion(
				t,
				[]string{
					"count",
					"depends_on",
					"for_each",
					"git_repository_link_id",
					"lifecycle",
					"location",
					"parent_connection",
					"provider",
					"timeouts",
					// DEBUG WriteOnly properties:
					// name - WriteOnly=false - IgnoreRead=false
					// cloneUri - WriteOnly=false - IgnoreRead=false
					// createTime - WriteOnly=false - IgnoreRead=false
					// updateTime - WriteOnly=false - IgnoreRead=false
					// deleteTime - WriteOnly=false - IgnoreRead=false
					// labels - WriteOnly=false - IgnoreRead=false
					// etag - WriteOnly=false - IgnoreRead=false
					// reconciling - WriteOnly=false - IgnoreRead=false
					// annotations - WriteOnly=false - IgnoreRead=false
					// uid - WriteOnly=false - IgnoreRead=false
					// terraformLabels - WriteOnly=false - IgnoreRead=false
					// effectiveLabels - WriteOnly=false - IgnoreRead=false
					// effectiveAnnotations - WriteOnly=false - IgnoreRead=false
					// location - WriteOnly=false - IgnoreRead=false
					// parent_connection - WriteOnly=false - IgnoreRead=false
					// gitRepositoryLinkId - WriteOnly=false - IgnoreRead=false
				},
				"google_developer_connect_git_repository_link",
			)
		})
	}
}
