// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package searchandconversation

import (
	"reflect"

	"github.com/GoogleCloudPlatform/terraform-google-conversion/v5/tfplan2cai/converters/google/resources/cai"
	"github.com/hashicorp/terraform-provider-google-beta/google-beta/tpgresource"
	transport_tpg "github.com/hashicorp/terraform-provider-google-beta/google-beta/transport"
)

const SearchAndConversationDataStoreAssetType string = "discoveryengine.googleapis.com/DataStore"

func ResourceConverterSearchAndConversationDataStore() cai.ResourceConverter {
	return cai.ResourceConverter{
		AssetType: SearchAndConversationDataStoreAssetType,
		Convert:   GetSearchAndConversationDataStoreCaiObject,
	}
}

func GetSearchAndConversationDataStoreCaiObject(d tpgresource.TerraformResourceData, config *transport_tpg.Config) ([]cai.Asset, error) {
	name, err := cai.AssetName(d, config, "//discoveryengine.googleapis.com/projects/{{project}}/locations/{{location}}/collections/{{collection_id}}/dataStores/{{data_store_id}}")
	if err != nil {
		return []cai.Asset{}, err
	}
	if obj, err := GetSearchAndConversationDataStoreApiObject(d, config); err == nil {
		return []cai.Asset{{
			Name: name,
			Type: SearchAndConversationDataStoreAssetType,
			Resource: &cai.AssetResource{
				Version:              "v1alpha",
				DiscoveryDocumentURI: "https://www.googleapis.com/discovery/v1/apis/discoveryengine/v1alpha/rest",
				DiscoveryName:        "DataStore",
				Data:                 obj,
			},
		}}, nil
	} else {
		return []cai.Asset{}, err
	}
}

func GetSearchAndConversationDataStoreApiObject(d tpgresource.TerraformResourceData, config *transport_tpg.Config) (map[string]interface{}, error) {
	obj := make(map[string]interface{})
	industryVerticalProp, err := expandSearchAndConversationDataStoreIndustryVertical(d.Get("industry_vertical"), d, config)
	if err != nil {
		return nil, err
	} else if v, ok := d.GetOkExists("industry_vertical"); !tpgresource.IsEmptyValue(reflect.ValueOf(industryVerticalProp)) && (ok || !reflect.DeepEqual(v, industryVerticalProp)) {
		obj["industryVertical"] = industryVerticalProp
	}
	displayNameProp, err := expandSearchAndConversationDataStoreDisplayName(d.Get("display_name"), d, config)
	if err != nil {
		return nil, err
	} else if v, ok := d.GetOkExists("display_name"); !tpgresource.IsEmptyValue(reflect.ValueOf(displayNameProp)) && (ok || !reflect.DeepEqual(v, displayNameProp)) {
		obj["displayName"] = displayNameProp
	}
	solutionTypesProp, err := expandSearchAndConversationDataStoreSolutionTypes(d.Get("solution_types"), d, config)
	if err != nil {
		return nil, err
	} else if v, ok := d.GetOkExists("solution_types"); !tpgresource.IsEmptyValue(reflect.ValueOf(solutionTypesProp)) && (ok || !reflect.DeepEqual(v, solutionTypesProp)) {
		obj["solutionTypes"] = solutionTypesProp
	}

	return obj, nil
}

func expandSearchAndConversationDataStoreIndustryVertical(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	return v, nil
}

func expandSearchAndConversationDataStoreDisplayName(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	return v, nil
}

func expandSearchAndConversationDataStoreSolutionTypes(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	return v, nil
}
