// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package cloudrunv3

import (
	"fmt"

	"github.com/GoogleCloudPlatform/terraform-google-conversion/v5/tfplan2cai/converters/google/resources/cai"
	"github.com/hashicorp/terraform-provider-google-beta/google-beta/tpgresource"
	transport_tpg "github.com/hashicorp/terraform-provider-google-beta/google-beta/transport"
)

// Provide a separate asset type constant so we don't have to worry about name conflicts between IAM and non-IAM converter files
const CloudRunV3ServiceIAMAssetType string = "run.googleapis.com/Service"

func ResourceConverterCloudRunV3ServiceIamPolicy() cai.ResourceConverter {
	return cai.ResourceConverter{
		AssetType:         CloudRunV3ServiceIAMAssetType,
		Convert:           GetCloudRunV3ServiceIamPolicyCaiObject,
		MergeCreateUpdate: MergeCloudRunV3ServiceIamPolicy,
	}
}

func ResourceConverterCloudRunV3ServiceIamBinding() cai.ResourceConverter {
	return cai.ResourceConverter{
		AssetType:         CloudRunV3ServiceIAMAssetType,
		Convert:           GetCloudRunV3ServiceIamBindingCaiObject,
		FetchFullResource: FetchCloudRunV3ServiceIamPolicy,
		MergeCreateUpdate: MergeCloudRunV3ServiceIamBinding,
		MergeDelete:       MergeCloudRunV3ServiceIamBindingDelete,
	}
}

func ResourceConverterCloudRunV3ServiceIamMember() cai.ResourceConverter {
	return cai.ResourceConverter{
		AssetType:         CloudRunV3ServiceIAMAssetType,
		Convert:           GetCloudRunV3ServiceIamMemberCaiObject,
		FetchFullResource: FetchCloudRunV3ServiceIamPolicy,
		MergeCreateUpdate: MergeCloudRunV3ServiceIamMember,
		MergeDelete:       MergeCloudRunV3ServiceIamMemberDelete,
	}
}

func GetCloudRunV3ServiceIamPolicyCaiObject(d tpgresource.TerraformResourceData, config *transport_tpg.Config) ([]cai.Asset, error) {
	return newCloudRunV3ServiceIamAsset(d, config, cai.ExpandIamPolicyBindings)
}

func GetCloudRunV3ServiceIamBindingCaiObject(d tpgresource.TerraformResourceData, config *transport_tpg.Config) ([]cai.Asset, error) {
	return newCloudRunV3ServiceIamAsset(d, config, cai.ExpandIamRoleBindings)
}

func GetCloudRunV3ServiceIamMemberCaiObject(d tpgresource.TerraformResourceData, config *transport_tpg.Config) ([]cai.Asset, error) {
	return newCloudRunV3ServiceIamAsset(d, config, cai.ExpandIamMemberBindings)
}

func MergeCloudRunV3ServiceIamPolicy(existing, incoming cai.Asset) cai.Asset {
	existing.IAMPolicy = incoming.IAMPolicy
	return existing
}

func MergeCloudRunV3ServiceIamBinding(existing, incoming cai.Asset) cai.Asset {
	return cai.MergeIamAssets(existing, incoming, cai.MergeAuthoritativeBindings)
}

func MergeCloudRunV3ServiceIamBindingDelete(existing, incoming cai.Asset) cai.Asset {
	return cai.MergeDeleteIamAssets(existing, incoming, cai.MergeDeleteAuthoritativeBindings)
}

func MergeCloudRunV3ServiceIamMember(existing, incoming cai.Asset) cai.Asset {
	return cai.MergeIamAssets(existing, incoming, cai.MergeAdditiveBindings)
}

func MergeCloudRunV3ServiceIamMemberDelete(existing, incoming cai.Asset) cai.Asset {
	return cai.MergeDeleteIamAssets(existing, incoming, cai.MergeDeleteAdditiveBindings)
}

func newCloudRunV3ServiceIamAsset(
	d tpgresource.TerraformResourceData,
	config *transport_tpg.Config,
	expandBindings func(d tpgresource.TerraformResourceData) ([]cai.IAMBinding, error),
) ([]cai.Asset, error) {
	bindings, err := expandBindings(d)
	if err != nil {
		return []cai.Asset{}, fmt.Errorf("expanding bindings: %v", err)
	}

	name, err := cai.AssetName(d, config, "//run.googleapis.com/projects/{{project}}/locations/{{location}}/services/{{name}}")
	if err != nil {
		return []cai.Asset{}, err
	}

	return []cai.Asset{{
		Name: name,
		Type: CloudRunV3ServiceIAMAssetType,
		IAMPolicy: &cai.IAMPolicy{
			Bindings: bindings,
		},
	}}, nil
}

func FetchCloudRunV3ServiceIamPolicy(d tpgresource.TerraformResourceData, config *transport_tpg.Config) (cai.Asset, error) {
	// Check if the identity field returns a value
	if _, ok := d.GetOk("location"); !ok {
		return cai.Asset{}, cai.ErrEmptyIdentityField
	}
	if _, ok := d.GetOk("name"); !ok {
		return cai.Asset{}, cai.ErrEmptyIdentityField
	}

	return cai.FetchIamPolicy(
		CloudRunV3ServiceIamUpdaterProducer,
		d,
		config,
		"//run.googleapis.com/projects/{{project}}/locations/{{location}}/services/{{name}}",
		CloudRunV3ServiceIAMAssetType,
	)
}
