// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package edgenetwork

import (
	"fmt"

	"github.com/GoogleCloudPlatform/terraform-google-conversion/v2/cai2hcl/common"
	"github.com/GoogleCloudPlatform/terraform-google-conversion/v2/caiasset"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-provider-google-beta/google-beta/tpgresource"
	transport_tpg "github.com/hashicorp/terraform-provider-google-beta/google-beta/transport"
)

const EdgenetworkSubnetAssetType string = "edgenetwork.googleapis.com/Subnet"

const EdgenetworkSubnetAssetNameRegex string = "projects/(?P<project>[^/]+)/locations/(?P<location>[^/]+)/zones/(?P<zone>[^/]+)/subnets"

type EdgenetworkSubnetConverter struct {
	name   string
	schema map[string]*schema.Schema
}

func NewEdgenetworkSubnetConverter(name string, schema map[string]*schema.Schema) common.Converter {
	return &EdgenetworkSubnetConverter{
		name:   name,
		schema: schema,
	}
}

func (c *EdgenetworkSubnetConverter) Convert(assets []*caiasset.Asset) ([]*common.HCLResourceBlock, error) {
	var blocks []*common.HCLResourceBlock
	config := common.NewConfig()

	for _, asset := range assets {
		if asset == nil {
			continue
		}
		if asset.Resource != nil && asset.Resource.Data != nil {
			block, err := c.convertResourceData(asset, config)
			if err != nil {
				return nil, err
			}
			blocks = append(blocks, block)
		}
	}
	return blocks, nil
}

func (c *EdgenetworkSubnetConverter) convertResourceData(asset *caiasset.Asset, config *transport_tpg.Config) (*common.HCLResourceBlock, error) {
	if asset == nil || asset.Resource == nil || asset.Resource.Data == nil {
		return nil, fmt.Errorf("asset resource data is nil")
	}

	assetResourceData := asset.Resource.Data

	hcl, _ := resourceEdgenetworkSubnetRead(assetResourceData, config)

	ctyVal, err := common.MapToCtyValWithSchema(hcl, c.schema)
	if err != nil {
		return nil, err
	}

	resourceName := assetResourceData["name"].(string)

	return &common.HCLResourceBlock{
		Labels: []string{c.name, resourceName},
		Value:  ctyVal,
	}, nil
}

func resourceEdgenetworkSubnetRead(resource map[string]interface{}, config *transport_tpg.Config) (map[string]interface{}, error) {
	result := make(map[string]interface{})
	var resource_data *schema.ResourceData = nil

	result["name"] = flattenEdgenetworkSubnetName(resource["name"], resource_data, config)
	result["labels"] = flattenEdgenetworkSubnetLabels(resource["labels"], resource_data, config)
	result["description"] = flattenEdgenetworkSubnetDescription(resource["description"], resource_data, config)
	result["create_time"] = flattenEdgenetworkSubnetCreateTime(resource["createTime"], resource_data, config)
	result["update_time"] = flattenEdgenetworkSubnetUpdateTime(resource["updateTime"], resource_data, config)
	result["network"] = flattenEdgenetworkSubnetNetwork(resource["network"], resource_data, config)
	result["ipv4_cidr"] = flattenEdgenetworkSubnetIpv4Cidr(resource["ipv4Cidr"], resource_data, config)
	result["ipv6_cidr"] = flattenEdgenetworkSubnetIpv6Cidr(resource["ipv6Cidr"], resource_data, config)
	result["vlan_id"] = flattenEdgenetworkSubnetVlanId(resource["vlanId"], resource_data, config)
	result["state"] = flattenEdgenetworkSubnetState(resource["state"], resource_data, config)

	return result, nil
}

func flattenEdgenetworkSubnetName(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenEdgenetworkSubnetLabels(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenEdgenetworkSubnetDescription(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenEdgenetworkSubnetCreateTime(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenEdgenetworkSubnetUpdateTime(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenEdgenetworkSubnetNetwork(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return v
	}
	return tpgresource.ConvertSelfLinkToV1(v.(string))
}

func flattenEdgenetworkSubnetIpv4Cidr(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenEdgenetworkSubnetIpv6Cidr(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenEdgenetworkSubnetVlanId(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	// Handles the string fixed64 format
	if strVal, ok := v.(string); ok {
		if intVal, err := tpgresource.StringToFixed64(strVal); err == nil {
			return intVal
		}
	}

	// number values are represented as float64
	if floatVal, ok := v.(float64); ok {
		intVal := int(floatVal)
		return intVal
	}

	return v // let terraform core handle it otherwise
}

func flattenEdgenetworkSubnetState(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}
