// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package cloudscheduler_test

import (
	"testing"

	"github.com/GoogleCloudPlatform/terraform-google-conversion/v7/test"
)

func TestAccCloudSchedulerJob(t *testing.T) {
	t.Parallel()

	tests := []test.TestCase{
		{
			Name: "TestAccCloudSchedulerJob_schedulerJobPubsubExample",
		},
		{
			Name: "TestAccCloudSchedulerJob_schedulerJobHttpExample",
		},
		{
			Name: "TestAccCloudSchedulerJob_schedulerJobPausedExample",
		},
		{
			Name: "TestAccCloudSchedulerJob_schedulerJobAppEngineExample",
		},
		{
			Name: "TestAccCloudSchedulerJob_schedulerJobOauthExample",
		},
		{
			Name: "TestAccCloudSchedulerJob_schedulerJobOidcExample",
		},
		{
			Name: "TestAccCloudSchedulerJob_schedulerPausedExample",
		},
	}

	for _, tt := range tests {
		tt := tt

		t.Run(tt.Name, func(t *testing.T) {
			t.Parallel()

			if tt.Skip != "" {
				t.Skipf("Skipping %s test case: This case is currently disabled due to Issue.", tt.Name)
			}

			test.BidirectionalConversion(
				t,
				[]string{
					"count",
					"deletion_protection",
					"depends_on",
					"dynamic",
					"for_each",
					"lifecycle",
					"provider",
					"region",
					"timeouts",
				},
				"google_cloud_scheduler_job",
			)
		})
	}
}
